#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oauthlib
Version  : 1.0.3
Release  : 17
URL      : https://pypi.python.org/packages/source/o/oauthlib/oauthlib-1.0.3.tar.gz
Source0  : https://pypi.python.org/packages/source/o/oauthlib/oauthlib-1.0.3.tar.gz
Summary  : A generic, spec-compliant, thorough implementation of the OAuth request-signing logic
Group    : Development/Tools
License  : BSD-3-Clause
Requires: oauthlib-python
BuildRequires : blinker
BuildRequires : cffi
BuildRequires : cffi-python
BuildRequires : cryptography
BuildRequires : enum34-python
BuildRequires : idna-python
BuildRequires : ipaddress-python
BuildRequires : linecache2-python
BuildRequires : nose-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pyasn1-python
BuildRequires : pycparser
BuildRequires : pycparser-python
BuildRequires : pycrypto-python
BuildRequires : pyjwt-python
BuildRequires : python-dev
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : six-python
BuildRequires : traceback2-python
BuildRequires : unittest2-python

%description
OAuthLib
========
*A generic, spec-compliant, thorough implementation of the OAuth request-signing
logic.*

%package python
Summary: python components for the oauthlib package.
Group: Default

%description python
python components for the oauthlib package.


%prep
%setup -q -n oauthlib-1.0.3

%build
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python2 setup.py test || :
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}
python3 setup.py build -b py3 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
