#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : oauthlib
Version  : 3.1.0
Release  : 48
URL      : https://files.pythonhosted.org/packages/fc/c7/829c73c64d3749da7811c06319458e47f3461944da9d98bb4df1cb1598c2/oauthlib-3.1.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/fc/c7/829c73c64d3749da7811c06319458e47f3461944da9d98bb4df1cb1598c2/oauthlib-3.1.0.tar.gz
Summary  : A generic, spec-compliant, thorough implementation of the OAuth request-signing logic
Group    : Development/Tools
License  : BSD-3-Clause
Requires: oauthlib-license = %{version}-%{release}
Requires: oauthlib-python = %{version}-%{release}
Requires: oauthlib-python3 = %{version}-%{release}
Requires: blinker
Requires: cryptography
BuildRequires : blinker
BuildRequires : buildreq-distutils3
BuildRequires : cryptography
BuildRequires : linecache2-python
BuildRequires : nose-python
BuildRequires : pycrypto-python
BuildRequires : pyjwt-python
BuildRequires : python-mock
BuildRequires : six
BuildRequires : six-python
BuildRequires : traceback2-python
BuildRequires : unittest2-python

%description
===============================================
        
        *A generic, spec-compliant, thorough implementation of the OAuth request-signing
        logic for Python 2.7 and 3.4+.*

%package license
Summary: license components for the oauthlib package.
Group: Default

%description license
license components for the oauthlib package.


%package python
Summary: python components for the oauthlib package.
Group: Default
Requires: oauthlib-python3 = %{version}-%{release}

%description python
python components for the oauthlib package.


%package python3
Summary: python3 components for the oauthlib package.
Group: Default
Requires: python3-core
Provides: pypi(oauthlib)

%description python3
python3 components for the oauthlib package.


%prep
%setup -q -n oauthlib-3.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586393261
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/oauthlib
cp %{_builddir}/oauthlib-3.1.0/LICENSE %{buildroot}/usr/share/package-licenses/oauthlib/5f350c5a2f0fb712d78b3203f40d1f9d3b399a31
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/oauthlib/5f350c5a2f0fb712d78b3203f40d1f9d3b399a31

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
